In [199]:
class StackWithMin:
    def __init__(self):
        self.content = []
        
    def __bool__(self):
        return bool(self.content)
    
    def push(self, v):
        if not self:
            self.content.append((v, v))
        else:
            self.content.append((v, min(self.content[-1][1], v)))
        
    def pop(self):
        return self.content.pop()[0]
    
    def get_min(self):
        if not self.content:
            return 9999
        
        return self.content[-1][1]

In [200]:
class QueueWithMin:
    def __init__(self):
        self.stack_a = StackWithMin()
        self.stack_b = StackWithMin()
        
    def push(self, v):
        self.stack_a.push(v)
        
    def pop(self):
        if not self.stack_b:
            while self.stack_a:
                self.stack_b.push(self.stack_a.pop())
        return self.stack_b.pop()
    
    def get_min(self):
        return min(self.stack_a.get_min(), self.stack_b.get_min())

In [34]:
A = [[1, 2, 3], [0, 0, 1], [3, 2, 1]]
# np.dot(A, A)]
np.linalg.det(A)

4.000000000000001

In [42]:
# 1
A = np.array([2-1j, 3+1j]).reshape(2,1)
B = np.array([1j, 1-1j])
np.conj(A).T @ B

array([1.-2.j])

In [45]:
# 2
pauli_x = np.array([[0 + 0j, 1 + 0j], [1 + 0j, 0 + 0j]])
pauli_y = np.array([[0 + 0j, 0 - 1j], [0 + 1j, 0 + 0j]])
pauli_z = np.array([[1 + 0j, 0 + 0j], [0 + 0j, 0j - 1]])

In [65]:
V = np.array([0, 1]).reshape(2, 1)
lambd = -1
np.allclose(np.dot(pauli_z, V), lambd * V)

True

In [62]:
lambd * V

array([[1.+0.j],
       [0.-1.j]])

In [50]:
print(np.linalg.eig(pauli_z))

(array([ 1.+0.j, -1.+0.j]), array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]]))


In [66]:
basis_0 = np.array([1 + 0j, 0 + 0j]).reshape((2, 1))
basis_1 = np.array([0 + 0j, 1 + 0j]).reshape((2, 1))
R = (basis_0 + 1j * basis_1) / np.sqrt(2)

In [67]:
print(R.conj().T @ pauli_y @ R)

[[1.+0.j]]


In [68]:
def u1(state, phi):
    return np.array([[1, 0], [0, np.exp(1j * phi)]]) @ state

In [70]:
phi = 0.1
U1 = np.array([[1, 0], [0, np.exp(1j * phi)]])
U1

array([[1.        +0.j        , 0.        +0.j        ],
       [0.        +0.j        , 0.99500417+0.09983342j]])

In [71]:
np.linalg.eig(U1)

(array([1.        +0.j        , 0.99500417+0.09983342j]),
 array([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]]))

In [ ]:
basis_0 = np.array([1 + 0j, 0 + 0j]).reshape((2, 1))
basis_1 = np.array([0 + 0j, 1 + 0j]).reshape((2, 1))

V = basis_0
lambd = -1
np.allclose(np.dot(pauli_z, V), lambd * V)

In [84]:
cmath.exp(1j*np.pi/2)

(6.123233995736766e-17+1j)

In [92]:
# 4: if basis_1 turn with r and mesure for Y we get |R>
def rx(state, phi):
    return np.array([
        [np.cos(phi / 2), -1j * np.sin(phi / 2)],
        [1j * np.sin(phi / 2),  np.cos(phi / 2)]
    ]) @ state

def expval(state, op):
    return state.conj().T @ op @ state

expval(rx(basis_1, np.pi / 2), pauli_y), expval(rx(basis_1, -np.pi / 2), pauli_y)


(array([[1.+0.j]]), array([[-1.+0.j]]))

In [93]:
R[0], R[1]

(array([0.70710678+0.j]), array([0.+0.70710678j]))

In [96]:
H = np.array([[1,1], [1, -1]])
H

array([[ 1,  1],
       [ 1, -1]])

In [108]:
basis = np.array([1 + 0j, 0 + 0j]).reshape((2, 1))
identity_gate = np.eye(2, dtype=np.complex128)
h = 1 / np.sqrt(2) * np.array([[1 + 0j, 1 + 0j], [1 + 0j, 0j - 1]])

np.dot(np.dot(pauli_z, H), pauli_z)

array([[ 1.+0.j, -1.+0.j],
       [-1.+0.j, -1.+0.j]])

In [103]:
pauli_x

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [106]:
pauli_z

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

In [121]:
# H x I
A = np.kron(h, identity_gate)

In [115]:
cnot = (1 + 0j) * np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
    ]
)
cnot

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

In [116]:
def ry(state, phi):
    return np.array([
        [np.cos(phi / 2), -np.sin(phi / 2)],
        [np.sin(phi / 2),  np.cos(phi / 2)]
    ]) @ state

In [123]:
cnot
ry(h, 0.7)

array([[ 0.42177145+0.j,  0.90670218+0.j],
       [ 0.90670218+0.j, -0.42177145+0.j]])

In [138]:
C = np.kron(basis_0, basis_0)

In [126]:
cnot = 

array([[1., 0.],
       [0., 1.]])

In [127]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [136]:
B = np.concatenate(
    (
        np.concatenate((np.eye(2), np.zeros((2,2)))),
        np.concatenate((np.zeros((2,2)), ry(h, 0.7)))
    ), axis=1
)

In [140]:
K = A @ B @ C

In [161]:
np.dot(K.reshape(1,4), np.array([0,1,10,11]))

array([7.07106781+0.j])

In [152]:
K

array([[0.70710678+0.j],
       [0.        +0.j],
       [0.70710678+0.j],
       [0.        +0.j]])

In [158]:
K.reshape(1,4)

array([[0.70710678+0.j, 0.        +0.j, 0.70710678+0.j, 0.        +0.j]])